name: Run Unit Test by pytest
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 単体テスト実行
      - name: PyTest
        run: |
          pytest -s ./tests
